run:
  timeout: 5m
  go: '1.23'

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  misspell:
    locale: US
