version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  misspell:
    locale: US
