version: "2"

run:
  timeout: 5m
  go: '1.23'

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - misspell
    - unconvert

formatters:
  enable:
    - gofmt
    - goimports

settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  goimports:
    local-prefixes: github.com/axonops/axonops-schema-registry
  misspell:
    locale: US
